### ISSUE TITLE
Update to NodeJS 21.5.0

### ISSUE THREAD

**Issue by Soft-Buddy** [puerts/backend-nodejs#10]
Update to compile latest NodeJS version. And implement patches to fix compile issue.

Excellent project btw...

**Comment by chexiongsheng** [comment]
This repository is mainly used by Puerts. Currently, Puerts does not have the need to upgrade Node to version 21.
Or you can refer to the changes and then submit them to us through a PR (Pull Request).

**Comment by Soft-Buddy** [comment]
I did succeed to update to Node 20.10.0 LTS, but it requires some modifications. Like running a custom docker container and adding Android linker binaries to path, etc to get it to compile successfully.

**Comment by shaggyyy2002** [comment]
I am trying to update it to v20. What all changes should i make? @Soft-Buddy @chexiongsheng
