### ISSUE TITLE
support for node c++ addons

### ISSUE THREAD

**Issue by ppchavan001** [puerts/backend-nodejs#13]
Does this Node.js backend support packages that use C++ addons, such as [koffi](https://www.npmjs.com/package/koffi)? 
I am encountering errors at statements like `require('koffi.node')` in Unreal engine 5.2 

If support is not currently available, are there any plans to include it in the future, or are there any workarounds to use these packages?

**Comment by chexiongsheng** [comment]
You need to recompile the Node.js C++ addons for your program, similar to how Node.js C++ addons require an electron-rebuild process to be used in Electron.

**Comment by ppchavan001** [comment]
I am not trying to create my own node C++ addons. I am trying to  use a npm package ([koffi](https://www.npmjs.com/package/koffi)) that uses C++ addons to function properly.
 
When I run the following script using system node (v16.16.0) its shows a message box. 
But  when I call this script from Unreal engine (puerts with node backend) I get 
`unhandledRejection,TypeError: koffi.load is not a function,TypeError`

I am guessing its because puerts is unable to load `koffi.node` file from `node_modules\koffi\build\koffi\win32_x64`


```npm install koffi```

```
import *  as koffi from 'koffi';

// Load the shared library
const lib = koffi.load('user32.dll');

// Declare constants
const MB_YESNO = 0x4;
const MB_ICONQUESTION = 0x20;
const MB_ICONINFORMATION = 0x40;
const IDYES = 6;

// Find functions
const MessageBoxA = lib.func('__stdcall', 'MessageBoxA', 'int', ['void *', 'str', 'str', 'uint']);
const MessageBoxW = lib.func('__stdcall', 'MessageBoxW', 'int', ['void *', 'str16', 'str16', 'uint']);

let ret = MessageBoxA(null, 'Do you want another message box?', 'Koffi', MB_YESNO | MB_ICONQUESTION);
if (ret == IDYES)
    MessageBoxW(null, 'Hello World!', 'Koffi', MB_ICONINFORMATION);
```

[koffi package doc](https://koffi.dev/start)

**Comment by chexiongsheng** [comment]
It is possible that your error is caused by the DefaultJSModuleLoader not looking for the koffi.node file. However, even if it finds the file, it will still fail to load because Node.js C++ addons include a reference to node.exe. At least on Windows, if the executable is not named node.exe, it will fail to load. For example, in the case of Electron, electron-rebuild recompiles and links to the Electron executable. However, currently, Puerts does not have similar support.

**Comment by ppchavan001** [comment]
I got it working for Win64 using MinHook.

I have tested the following Node modules in UE 5.2 on Windows without rebuilding any modules from source:

- [koffi](https://www.npmjs.com/package/koffi)
- [utf-8-validate](https://www.npmjs.com/package/utf-8-validate)
- [bufferutil](https://www.npmjs.com/package/bufferutil)
- [leveldown](https://www.npmjs.com/package/leveldown)
- [ref-napi](https://www.npmjs.com/package/ref-napi)
- [ffi-napi](https://www.npmjs.com/package/ffi-napi)
- [sqlite3](https://www.npmjs.com/package/sqlite3)
- [hmc-win32](https://www.npmjs.com/package/hmc-win32)
- [node-api-dotnet](https://www.npmjs.com/package/node-api-dotnet) (crashing during GC, probably due to some `dotnet.dll` unloading issue)
- [bcrypt](https://www.npmjs.com/package/bcrypt)
- [sharp](https://www.npmjs.com/package/sharp) (testing abandoned since this package requires Node 18 or higher)

You can review the changes in this [commit](https://github.com/ppchavan001/puerts/commit/d30f54ccb2d0f26c8059526b341d69d47f7d6bae).

If you have no further questions, you can close this issue.

**Comment by chexiongsheng** [comment]
This is a good attempt, but it's a bit hacker, I would rather provide a tool similar to electron-rebuild.
